// import NavBar from '@/components/NavBar'
// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>{children}</body>
//     </html>
//   )
// }

import NavBar from "@/components/NavBar";
import "./globals.css";
import { Inter, Roboto } from "next/font/google";
import Script from "next/script";
// import FlowBiteFooter from '@/components/Footer';
import Footer from "@/components/Footer";

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Torii Inmuebles",
  description: "Lo mejor en inmuebles",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={roboto.className}>
        <div className="container max-w-7xl mx-auto">
          <NavBar />
        </div>
        <div className="container max-w-7xl mx-auto px-2">{children}</div>
        <Footer />
        <Script
          src="../path/to/flowbite/dist/flowbite.min.js"
          strategy="worker"
        />
      </body>
    </html>
  );
}
